// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3XhWoB5mCiiT6KjLQkbwBIvsY5jlmT_w',
    appId: '1:218550087297:web:be149ac3230024148ae780',
    messagingSenderId: '218550087297',
    projectId: 'go1tok',
    authDomain: 'go1tok.firebaseapp.com',
    storageBucket: 'go1tok.appspot.com',
    measurementId: 'G-L940Z88X02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZJRxYZmX5rowI18q6rJWwyc4rDjV1VFM',
    appId: '1:218550087297:android:9277c296f826af398ae780',
    messagingSenderId: '218550087297',
    projectId: 'go1tok',
    storageBucket: 'go1tok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoQ8fB2hdBSnKDTe8sEbpEPawVetBxEvc',
    appId: '1:218550087297:ios:4d7199f156e6e1b18ae780',
    messagingSenderId: '218550087297',
    projectId: 'go1tok',
    storageBucket: 'go1tok.appspot.com',
    androidClientId: '218550087297-m4vpm29tri1goj31suqr5fi1gt2elubj.apps.googleusercontent.com',
    iosClientId: '218550087297-7ob5d9kcktblk3n5b37cfaa98vq9oodg.apps.googleusercontent.com',
    iosBundleId: 'com.midnight.greatdevelopers.go1tok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoQ8fB2hdBSnKDTe8sEbpEPawVetBxEvc',
    appId: '1:218550087297:ios:5139e2cf76558c188ae780',
    messagingSenderId: '218550087297',
    projectId: 'go1tok',
    storageBucket: 'go1tok.appspot.com',
    androidClientId: '218550087297-m4vpm29tri1goj31suqr5fi1gt2elubj.apps.googleusercontent.com',
    iosClientId: '218550087297-m3h8mcqckj3arl2m17uvtujec9diisgp.apps.googleusercontent.com',
    iosBundleId: 'com.midnight.greatdevelopers.go1tok.RunnerTests',
  );
}
